### ISSUE TITLE
Sprint #5 (3/8/20 - 9/8/20)

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/unified-codes#101]
Week 5 sprint (3/8/20 - 9/8/20).

@mark-prins:

- [x] Add redux-saga to web project: #94.
- [x] Handle apollo errors in web ui: #100. 
- [x] Fix nx web project paths: #110.
- [x] Add redux to web project: #112.

@katherine-sussol:

- [x] Product search fails with less than 3 chars in search term: #108 

@wlthomson:

- [x] Refactor automated testing using nx tools: #103.

**Comment by wlthomson** [comment]
@mark-prins @katherine-sussol Could we have a quick meeting sometime today to organise this?
