### ISSUE TITLE
Sprint #6 (10/8/20 - 16/8/20)

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/unified-codes#127]
Week 6 sprint (10/8/20 - 16/8/20).

@mark-prins:

- [x] Add frontend authorisation logic: #76 (+@wlthomson).
- [x] Entity Browser not returning results: #126.

@katherine-sussol:

- [x] Dockerise services: #99  (+@wlthomson).
- [x] Update universal code UI: https://github.com/sussol/msupply/issues/6549.
- [x] Remove web prettier config: #124.

@wlthomson:

- [x] Refactor docker scripts using nx tools: #104, #117.
- [x] Update monorepo projects with consistent formatting: #120.
