### ISSUE TITLE
Sprint #7 (17/8/20 - 23/8/20)

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/unified-codes#128]
Week 7 sprint (17/8/20 - 23/8/20)

@mark-prins:

- [x] Style the app bar: #131.

@katherine-sussol:

- [x] Dockerise services: #99.

@wlthomson:

- [x] Fix broken nx refactor #129.
- [x] Update alert actions: #142.
- [x] Tidy up nx refactor cruft: #143.
- [x] Add support for redux dev tools #136.
- [x] Remove Apollo client from web app: #137.
