### ISSUE TITLE
Sprint 8 (24/8/20 - 31/8/20)

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/unified-codes#148]
Week 8 sprint (24/8/20 - 31/8/20).

@mark-prins:

- [x] Create footer component: #153.
- [x] Update UI library storybooks #147.

@katherine-sussol:

- [x] Integrate building docker images with GitHub CI: #146.

@wlthomson:
- [x] Front-end auth issues: #132.

**Comment by katherine-sussol** [comment]
I'm going to close this one out and move the incomplete ones to the Week 9 sprint (which will have new items discussed today as well) - hopefully no objections!
