### ISSUE TITLE
Sprint #9 (31/8/20 - 6/9/20)

### ISSUE THREAD

**Issue by katherine-sussol** [openmsupply/unified-codes#165]
Week 9 sprint (31/8/20 - 6/9/20).

@mark-prins:

- [x] Add pagination to explorer #168.
- [x] Add filter to explorer request #170.

@katherine-sussol:

- [x] Create component(s) for toggling entity types to display: #155. 
 
@wlthomson:

On leave.

**Comment by wlthomson** [comment]
@katherine-sussol Thanks for organising the sprint 🙇‍♂️ . Slightly adjusted the formatting for consistency, but all looks good to me!

**Comment by wlthomson** [comment]
Housekeeping: have closed out previous sprint project (https://github.com/openmsupply/unified-codes/projects/14) and created new one corresponding to this sprint issue (https://github.com/openmsupply/unified-codes/projects/15).

![bart_nerd](https://user-images.githubusercontent.com/43223637/92464553-69bc1d80-f221-11ea-9833-7c94e4ac2fb5.gif)

**Comment by katherine-sussol** [comment]
Thanks for the housekeeping! 🧹 😸

**Comment by wlthomson** [comment]
Updated and closing!
