### ISSUE TITLE
Week 10 sprint (7/9/20 - 13/9/20)

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/unified-codes#188]
Week 10 sprint (7/9/20 - 13/9/20).

@mark-prins:

- [x] Apply styling to explorer: #152.
- [x] Add filter to explorer request: #170.
- [x] Add ordering of results to explorer: #174.

@katherine-sussol:

- [x] Add toggle button menu to web ui: #163.

@wlthomson:

On leave.

**Comment by wlthomson** [comment]
Housekeeping 🏠🧹.
