### ISSUE TITLE
Sprint #11 (14/9/20 - 20/9/20)

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/unified-codes#189]
Week 11 sprint (14/9/20 - 20/9/20).

@mark-prins:

- [x] Refactor entities redux shape: #175.
- [x] Tidy ui: #179.
- [x] Add mock data to explorer story: #183.
- [x] Investigate application hosting.

@katherine-sussol:

- [x] Start SearchResults page: #185 
- [x] Investigate external code/data exposure/lookup in GraphQL API: #164.
- [x] Fix nx storybook ui error: #181.

@wlthomson:

Returning from leave (reviews + catch up).

**Comment by wlthomson** [comment]
Sorry, a bit late on this one. Have backdated last couple of weeks by cross-referencing with PRs...

![seeya](https://user-images.githubusercontent.com/43223637/93660937-eebbf800-faa7-11ea-8885-62699a475401.gif)
