### ISSUE TITLE
Sprint #12 (21/9/20 - 27/9/20)

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/unified-codes#196]
Week 12 sprint (21/9/20 - 27/9/20).

@mark-prins:

- [x] Connect the type filter #195 
- [x] Update dependencies #194
- [x] Data service hosting issue #193

@katherine-sussol:

- [x] Start SearchResults page  #185
- [x] Layout for details page #198

@wlthomson:

- [x] Refactor EntityBrowser props #190
