### ISSUE TITLE
Sprint #13 (27/9/20 - 4/10/20)

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/unified-codes#210]
Week 13 sprint (26/9/20 - 1/10/20).

@mark-prins:

- On leave.

@katherine-sussol:

- [x]  Layout for details page #198.

@wlthomson:

- [x] Refactor EntityBrowser props #190.
- [x] Add theme context to redux refactor branch #205.
