### ISSUE TITLE
Sprint #14 (5/10/20 - 11/10/20) 

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/unified-codes#211]
@mark-prins:
- [ ] Display drug interactions in mSupply: [#6974](https://github.com/sussol/msupply/issues/6974).

@katherine-sussol:
- [x] Migrate entity details saga to updated app structure: https://github.com/openmsupply/unified-codes/issues/212.
- [x] Add drug interactions back into data-service: #216.
- [x] Decouple GraphQL schema types from Dgraph: #219 
 
@wlthomson:

- [x] Add shared web app styles imports: #186.
- [x] Refactor web and library components: #187.
- [x] Migrate details page to reduxified app: #209.
- [x] Add reducers to redux refactor branch #206.
- [x] Add minimal entity details interface: #214.
