### ISSUE TITLE
Sprint #15 (12/10/20 - 18/10/20)

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/unified-codes#248]
@mark-prins 

- [x] Add loading indicator to explorer: #229.
- [x] Circular dependency errors: #233.
- [x] Connect pagination #235.
- [x] Pagination to show on screen: #238.
- [x] Code formatting update: #242.

@katherine-sussol 

- [x] Missing prop key and grid direction on details page: #246.

@wlthomson 

- [x] Organise app components: #222.
- [x] Add List components: #223.
- [x] Migrate data service to TypeGraphQL: #239.
