### ISSUE TITLE
Sprint #16 (19/10/20 - 25/10/20)

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/unified-codes#261]
@mark-prins 

- [x] Display drug interactions in mSupply: #6974.
- [x] Data fetch notification timing: #218.
- [x] Unable to build web: #264.
- [x] Unable to fetch data: #265.

@katherine-sussol 

- [x] Improve combination drug representation for interactions: #245.
- [x] Data service schema mandatory fields: #171.

@wlthomson 

- [x] Update graph schema: #257.
