### ISSUE TITLE
Sprint #17 (26/10/20 - 1/11/20)

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/unified-codes#262]
@mark-prins 

- [x] Unable to build web: #264.
- [x] Unable to fetch data: #265.

@katherine-sussol 

- [x] Migrate migration scripts: #272.

@wlthomson 

- [x] Update graph schema #257.
