### ISSUE TITLE
Sprint #18 (2/8/20 - 8/8/20)

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/unified-codes#288]
@mark-prins 

- [x] Insufficient cats: #268.
- [x] Narrow entity query search: #259.
- [x] Return properties of parent: #276.

@katherine-sussol 

- [x] Migrate migration scripts: #272.

@wlthomson 

- [x] Update graph schema #257
- [x] Remove legacy-api project: #271.
