### ISSUE TITLE
Sprint #19 (9/11/20 - 15/11/20)

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/unified-codes#289]
@mark-prins 

- [x] Refactor interactions resolver: #281.
- [x] Display lower level item codes: #283.

@katherine-sussol 

- [x] Migrate migration scripts: #272.
- [x] Update main README.md file: #285.

@wlthomson 

- [x] Patch UC functionality to versioned graph schema: #7237.
- [x] Update graph schema: #257.
