### ISSUE TITLE
Sprint #20 (16/10/20 - 22/10/20)

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/unified-codes#290]
@mark-prins 

- On call 📞 .
- [x] Http2 issue on server: #294.

@katherine-sussol 

- [x] Migrate migration scripts: #272.
- [x] Migrate v1 entity resolvers to v2 backend: #296.

@wlthomson 

- [x] Update Dgraph Schema: #266.
- [x] Migrate v1 resolvers to v2 backend: #291.
- [ ] Tidy up dgraph data: #297.
