### ISSUE TITLE
Sprint #1 (6/7/20 - 12/7/20)

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/unified-codes#30]
Week 1 sprint (6/7/20 - 12/7/20).

Issues:

@katherine-sussol 

- [x] Add initial backend GraphQL schema: #29.

@mark-prins 

- [x] Migrate existing universal codes data to Dgraph: #31.

@wlthomson 

- [x] Add additional API test cases: #27.
- [x] Fix Dgraph script not running on Windows: #34.
- [x] Update v1 API compatibility with mSupply: #36.
- [x] Add issue and PR templates: #38.
- [x] Add jest continuous integration: #40.
- [x] Add additional tests for graph backend: #43.
- [x] Fix failing graph tests: #45.
- [x] Fix mSupply universal codes lookup whitespace bug: [sussol/msupply #6560](https://github.com/sussol/msupply/issues/6560).
