### ISSUE TITLE
Sprint #2 (13/7/20 - 19/7/20)

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/unified-codes#50]
Week 2 sprint (6/7/20 - 12/7/20).

Issues:

@katherine-sussol 

- [x] Add Apollo backend: #52 (+ @wlthomson).

@mark-prins 

- [x] Additional data migration: #31.
- [x] UI wireframes.

@wlthomson 

- [x] Initialise UI project: #51.
