### ISSUE TITLE
Sprint #3 (19/7/20 - 26/7/20)

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/unified-codes#68]
Week 3 sprint (19/7/20 - 26/7/20).

Issues:

@katherine-sussol 

- [x] Update GraphQL schema (Entity query): #67.
- [x] Drug interaction lookup: #41 (+@mark-prins).

@mark-prins 

- [x] Backend authorisation logic: #66.

@wlthomson 

- [x] Add GraphQL client to web UI: #56.
- [x] Add logic for populating table with products: #70.
- [x] Add UI searchbar/input components: #71.
- [x] Refactor dgraph project structure: #79.
- [x] Add prettier config to web project: #83.
- [x] Refactor web project components, types: #85.
- [x] Add EntityBrowser component: #86.

**Comment by wlthomson** [comment]
Update: all issues have been PRed (merged or awaiting review). Sprint is mostly complete, but will delay closing until all PRs are merged.
