### ISSUE TITLE
Legacy API discussion (v2.0.0)

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/unified-codes#9]
## Description

Epic for planning and tracking RESTful legacy API tasks for v2.0.0.

## Scope

- Setup repo structure, e.g. `unified-codes/api`.
- Add core dependencies: `fastify`, `jest`.
- Add skeleton code for `v1` endpoints.
- Add mock data, test cases for endpoints.
- Add logic for mapping `v1` HTTP requests to graphql queries.
- Add logic for mapping graphql responses to `v1` response format.

## Issues:

- [x] Authorisation/access control by the Dgraph server: #6.
- [x] Initialise RESTful API project: #12.
- [x] Expand rest api test data: #14.
- [x] Expand rest api test suite to cover existing v1 functionality: #15.
- [x] Add functionality for v1 endpoints: #19.
- [x] Map REST queries to Dgraph queries: #20.
- [x] Error in response mapper: #22.
- [x] Items endpoint failing invalid params test: #25.
- [x] Add additional API test cases API enhancement: #27. 
- [x] Convert existing v1 API to typescript: #32.
- [x] Add jest continuous integration: #40.
- [x] Add additional tests for graph backend #43.
- [x] Fix failing graph tests: #45.
- [x] Add repo wiki: #48.
- [x] Refactor repo as nx monorepo: #58.
- [ ] Update legacy API to query Apollo schema: #73.
- [ ] Add initial API docs: #81.
- [x] Dockerise services: #99.
- [x] Refactor automated testing using nx tools: #103.
- [ ] Add docker orchestration tools: #106.
- [x] Product search fails with less than 3 chars in search term: #108.
- [x] Add search by partial code to legacy api: #118.
- [x] Update monorepo projects with consistent formatting: #120.
- [x] Fix broken nx refactor: #129.
- [x] Integrate building docker images with GitHub CI: #146.
- [ ] Split docker-compose into local and deployed version: #151.
- [ ] Add commit hook to lint and type check code: #158.
- [x] Data service hosting issue: #193.
- [x] Update dependencies: #194.

**Comment by katherine-sussol** [comment]
Note for posterity: #271 `legacy-api` was removed and all queries now routed via GraphQL API.
